# aqua - Declarative CLI Version Manager
# https://aquaproj.github.io/
registries:
  - type: standard
    ref: v3.59.0 # renovate: depName=aquaproj/aqua-registry
packages:
  - name: x-motemen/ghq@v1.3.0
  - name: peco/peco@v0.5.10
  - name: stedolan/jq@jq-1.6
  - name: lima-vm/lima@v0.12.0
  - name: hashicorp/terraform@v1.3.0
  - name: golang/go@go1.19
